// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kobrbubbfblaydoimoti.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtvYnJidWJiZmJsYXlkb2ltb3RpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQwNzkwMzMsImV4cCI6MjA1OTY1NTAzM30.UeUEO0YMkPeDhAHBnnkwZzeWtn0k7tvI3AxYcDCcSwI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);